### ISSUE TITLE
(0 , _reactNativeRedash.onGestureEvent) is not a function

### ISSUE THREAD

**Issue by HoaiHuynh** [13773753970/react-native-card-modal-reanimated#1]
Hi all, I have installed and use this lib, but I have a bug. How do I fix it?

![image](https://user-images.githubusercontent.com/37495328/92843406-e829e280-f40e-11ea-8d4b-a7c936014928.png)

**Comment by pengzhouer** [comment]
I am sorry, I didn’t see it before. And I am busy recently. I think this fault may be caused by redash version, in v2 redash support Reanimated2, but now reanimated2 is unstable, you can try to install redash v1 in your project, and be noticed about the dependence’s version.
I will check the problem carefully after these days.
I am happy you like this project😁
And I will continue update it follow reanimated v2!
